app:
  title: Enterprise Developer Portal
  baseUrl: https://backstage-pranab-mvp.azurewebsites.net

organization:
  name: Enterprise Platform

backend:
  baseUrl: https://backstage-pranab-mvp.azurewebsites.net
  listen:
    host: 0.0.0.0
    port: 8080
  cors:
    origin: https://backstage-pranab-mvp.azurewebsites.net
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: /home/data/backstage.db

auth:
  environment: production
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Template, User, Group]
  locations:
    - type: file
      target: ./examples/infrastructure-template/template.yaml
      rules:
        - allow: [Template]
