app:
  title: Enterprise Developer Portal
  baseUrl: http://localhost:3000
  packages: all
  extensions:
    - page:catalog:
        config:
          path: /

organization:
  name: Enterprise Platform

auth:
  environment: development
  providers:
    guest: {}

catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    - type: file
      target: ./examples/infrastructure-template/template.yaml
      rules:
        - allow: [Template]
