app:
  title: Enterprise Developer Portal
  baseUrl: http://localhost:3000

  # Enable all packages by default, this will discover packages from packages/app/package.json
  packages: all

  extensions:
    # Configure the catalog index page to be the root page, this is normally mounted on /catalog
    - page:catalog:
        config:
          path: /

organization:
  name: Enterprise Platform

auth:
  environment: development
  providers:
    guest: {}

catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    - type: file
      target: ./examples/infrastructure-template/template.yaml
      rules:
        - allow: [Template]
